library(DBI)  # For database connection
library(tidyverse) # Contains dplyr for tidy-querying and ggplot for data Viz...

con <- dbConnect(odbc::odbc(), 
                 .connection_string = 
                   "Driver={MySQL ODBC 8.1 Unicode Driver};", 
                 server = "localhost", 
                 Database = "sakila", 
                 UID = "root", 
                 PWD = "test1234",
                 port = 3306)

# Selecting tables and load into R
query1 <- "SELECT * FROM film"
film <- dbGetQuery(con, query1)

query2 <- "SELECT * FROM inventory"
inventory <- dbGetQuery(con, query2)

query3 <- "SELECT * FROM rental"
rental <- dbGetQuery(con, query3)

query4 <- "SELECT * FROM payment"
payment <- dbGetQuery(con, query4)

query5 <- "SELECT * FROM store"
store <- dbGetQuery(con, query5)

query6 <- "SELECT * FROM staff"
staff <- dbGetQuery(con, query6)

# Remember to disconnect from a connection after your query
# it is a good practice: Resource management, To avoid connection limits
# managing transactions, preventing resource leaks, security etc...

dbDisconnect(con)

# List the top 5 most frequently rented films and their rental count...
film |> 
  inner_join(inventory, by = 'film_id') |> 
  inner_join(rental, by = 'inventory_id') |> 
  group_by(film_id, title) |> 
  summarise(rental_count = n()) |> 
  arrange(desc(rental_count)) |> 
  head(5)


# find the revenue generated by each store:
store |> 
  inner_join(staff, by = 'store_id') |> 
  inner_join(payment, by = 'staff_id') |> 
  group_by(store_id) |> 
  summarize(total_revenue = sum(amount)) |> 
  head(5)


# Find the top 10 grossing films (by revenue):
film |> 
  inner_join(inventory, by = 'film_id') |> 
  inner_join(rental, by = 'inventory_id') |> 
  inner_join(payment, by = 'rental_id') |> 
  group_by(film_id, title) |> 
  summarise(total_revenue = sum(amount)) |> 
  arrange(desc(total_revenue)) |> 
  head(10) |> 
  # The plot added
  ggplot(aes(x = total_revenue, y = reorder(title,total_revenue)))+
  geom_bar(stat = 'identity', fill = 'darkblue')+
  theme_minimal()+
  theme(legend.position = 'none')+
  labs(y = 'Movies', x= 'Total revenue')

#-------------------------------------

# Direct SQL queries

# List the top 5 most frequently rented films and their rental count...
sql1 <-
  "SELECT f.film_id, f.title, COUNT(*) AS rental_count
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.film_id, f.title
ORDER BY rental_count DESC
LIMIT 5;"

dbGetQuery(con, sql1)


# find the revenue generated by each store
sql2<- 
  "SELECT s.store_id, SUM(p.amount) AS total_revenue
FROM store s
JOIN staff st ON s.store_id = st.store_id
JOIN payment p ON st.staff_id = p.staff_id
GROUP BY s.store_id;"

dbGetQuery(con, sql2)


# find the top 10 grossing films (by revenue):
sql3 <-
  "SELECT f.film_id, f.title, SUM(p.amount) AS total_revenue
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
JOIN payment p ON r.rental_id = p.rental_id
GROUP BY f.film_id, f.title
ORDER BY total_revenue DESC
LIMIT 10;"

dbGetQuery(con, sql3)|> 
  # The plot added
  ggplot(aes(x = total_revenue, y = reorder(title,total_revenue)))+
  geom_bar(stat = 'identity', fill = 'darkblue')+
  theme_minimal()+
  theme(legend.position = 'none')+
  labs(y = 'Movies', x= 'Total revenue')
